import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Provider} from "jotai"
import TopBar from "@/components/topBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
      </head>
      <body className={inter.className} data-theme="forest">
        <main className="">
            {/* Init Jotai */}
            <Provider>
                <TopBar />
                {children}
            </Provider>
        </main>
      </body>
    </html>
  );
}
